version: '3.9'

services:
  nginx:
    build:
      context: .
      target: nginx_base
    volumes:
      - ./:/srv/app:ro,cached
      - php_socket:/var/run/php
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app

  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    environment:
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    depends_on:
      - database
    networks:
      - app

  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tourney}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-tourney}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app

volumes:
  database_data:
  php_socket:

networks:
  app:
    driver: bridge
